
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: cvflow
      POSTGRES_USER: cvuser
      POSTGRES_PASSWORD: cvpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cvflow_api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://cvuser:cvpass@postgres:5432/cvflow

volumes:
  pgdata:
