services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile
    container_name: cvflow_api
    ports:
      - "8000:8000"
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./data/storage-db:/app/data/storage-db
    environment:
      - UPLOAD_DIR=/app/data/uploads
      - DATABASE_URL=postgresql://cvuser:cvpass@postgres_cvflow:5432/cvflow
      

    depends_on:
      - postgres
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # comunicación AMQP
      - "15672:15672"    # panel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: gues

  postgres:
    image: postgres:15
    container_name: postgres_cvflow
    restart: always
    environment:
      POSTGRES_USER: cvuser
      POSTGRES_PASSWORD: cvpass
      POSTGRES_DB: cvflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/uploads:/app/data/uploads
      - ./data/storage-db:/app/data/storage-db

volumes:
  postgres_data:
    driver: local

