# Dockerfile for FastAPI application
FROM python:3.11-slim


# Set environment variables
ENV PYTHONUNBUFFERED=1
WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y build-essential libpq-dev && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]